/**
 * PROJ-29 Block C — shared E2E test-tenant identifiers.
 *
 * Hardcoded UUIDs so the migration, the global-setup script, and any
 * test-specific data fixtures all agree on the same rows. The UUIDs are
 * clearly synthetic (trailing `e2e0..e2e2`) and are extremely unlikely
 * to collide with real production tenants/users.
 */

export const E2E_USER_ID = "00000000-0000-0000-0000-000000000e2e"
export const E2E_TENANT_ID = "00000000-0000-0000-0000-000000000e20"
export const E2E_TEST_EMAIL = "e2e-test@projektplattform-v3.test"
export const E2E_TEST_PASSWORD = "Test-Password-PROJ29!" // local-only, never deployed
export const E2E_TENANT_NAME = "[E2E] Projektplattform Test"

/**
 * PROJ-51-ε.4 — fixed-UUID seed project for Project-Room visual
 * regression. Pinned so snapshots reference a stable URL across runs
 * (otherwise dynamic UUIDs blow up every diff). `project_type` =
 * "general" keeps the seed minimal — no trigger-spawned phases or
 * sprints that would change between runs.
 */
export const E2E_PROJECT_ID = "00000000-0000-0000-0000-000000000e21"
export const E2E_PROJECT_NAME = "[E2E] Visual-Regression Project"

/**
 * Persisted Playwright storageState. Gitignored. Regenerated by
 * `npm run test:e2e:setup` (or implicitly on the first test run via
 * `globalSetup`).
 */
export const E2E_STORAGE_STATE_PATH = "tests/fixtures/.auth/storage-state.json"
