/**
 * PROJ-29 Block C — shared E2E test-tenant identifiers.
 *
 * Hardcoded UUIDs so the migration, the global-setup script, and any
 * test-specific data fixtures all agree on the same rows. They stay
 * obviously synthetic (`e2e…` prefix) and will not collide with real
 * production tenants/users.
 *
 * PROJ-143 — these MUST be RFC-4122 conformant. The original ids
 * (`00000000-0000-0000-0000-000000000e2e` / `…e20` / `…e21`) carried a
 * zero version and zero variant nibble, so they are not valid UUIDs. The
 * app validates with zod 4, whose `z.string().uuid()` enforces both — so
 * every request body or form field carrying one of these ids was rejected
 * with a 400 or a client-side validation error. Consequences seen in the
 * wild, worked around locally three times before the root cause was named:
 *
 *   - PROJ-70 F-3 / PROJ-89 F-3: the wizard-draft CREATE route rejects the
 *     tenant id, so drafts had to be seeded service-role.
 *   - PROJ-Y-78f: `responsible_user_id` is validated with `z.string()
 *     .uuid()`, so the E2E user could not get past step 1 of the wizard —
 *     the whole flow was untestable end-to-end.
 *
 * Real Supabase auth ids are v4, so this only ever affected the fixture.
 * Keep any replacement RFC-4122 conformant (version nibble 4, variant
 * nibble 8/9/a/b) — `assertConformantFixtureIds()` in `global-setup.ts`
 * hard-fails otherwise.
 *
 * (PROJ-Y-144d corrected this note: it used to point at a `constants.test.ts`
 * that does not exist. It could not exist either — `tests/**` is excluded from
 * vitest, which is why PROJ-143 put the guard in global-setup. Add new ids to
 * that guard's list, not to an imaginary unit test.)
 */

export const E2E_USER_ID = "e2e00000-0000-4e2e-8e2e-000000000001"
export const E2E_TENANT_ID = "e2e00000-0000-4e2e-8e2e-000000000002"
/**
 * Distinct from the pre-PROJ-143 address on purpose. `global-setup` treats
 * "already registered" as success and then signs in BY EMAIL — reusing the
 * old address would silently authenticate the old, non-conformant user and
 * make the migration a no-op.
 */
export const E2E_TEST_EMAIL = "e2e-rfc4122@projektplattform-v3.test"
export const E2E_TEST_PASSWORD = "Test-Password-PROJ29!" // local-only, never deployed
/** Unchanged: PROJ-51 visual-regression snapshots render this string. */
export const E2E_TENANT_NAME = "[E2E] Projektplattform Test"
/**
 * `tenants.domain` is UNIQUE and the pre-PROJ-143 tenant still holds
 * `e2e.projektplattform-v3.test`, so the new row needs its own.
 */
export const E2E_TENANT_DOMAIN = "e2e-rfc4122.projektplattform-v3.test"

/**
 * PROJ-51-ε.4 — fixed-UUID seed project for Project-Room visual
 * regression. Pinned so snapshots reference a stable URL across runs
 * (otherwise dynamic UUIDs blow up every diff). `project_type` =
 * "general" keeps the seed minimal — no trigger-spawned phases or
 * sprints that would change between runs.
 */
export const E2E_PROJECT_ID = "e2e00000-0000-4e2e-8e2e-000000000003"
export const E2E_PROJECT_NAME = "[E2E] Visual-Regression Project"

/**
 * PROJ-Y-144d — a SECOND test tenant, with the assistant module switched on.
 *
 * Why a separate tenant instead of enabling the module on `E2E_TENANT_ID`:
 * `AssistantLauncher` is mounted in `src/components/app/app-shell.tsx`, so an
 * active assistant module puts a `fixed` button on every signed-in page — and
 * `PROJ-51-visual-regression-authenticated.spec.ts` photographs exactly that
 * shell `fullPage`. Enabling it on the shared tenant would have altered those
 * baselines (and toggling it inside a spec would race the visual specs, since
 * Playwright parallelises files). Two tenants keep the two concerns apart:
 * the visual specs stay on a tenant where the assistant is off and the
 * launcher does not render.
 *
 * The separation only holds because the active tenant is pinned explicitly via
 * the `active_tenant_id` cookie in `auth-fixture.ts`. Do NOT rely on the
 * server's fallback (`resolveActiveTenantId` → earliest membership): with two
 * memberships created in the same second on a fresh environment, that ordering
 * is a coin flip.
 */
export const E2E_ASSISTANT_TENANT_ID = "e2e00000-0000-4e2e-8e2e-000000000004"
export const E2E_ASSISTANT_TENANT_NAME = "[E2E] Assistant Test"
export const E2E_ASSISTANT_TENANT_DOMAIN =
  "e2e-assistant.projektplattform-v3.test"

/**
 * Scrum on purpose: the method drives the work-item kind (`story`), so the
 * PROJ-144 mapping is actually exercised. `E2E_PROJECT_ID` carries
 * `project_method = null`, where every kind is allowed and the mapping is a
 * no-op — a chain test there would have proven nothing about the method rule.
 */
export const E2E_ASSISTANT_PROJECT_ID = "e2e00000-0000-4e2e-8e2e-000000000005"
export const E2E_ASSISTANT_PROJECT_NAME = "[E2E] Assistant Scrum Project"

/**
 * Persisted Playwright storageState. Gitignored. Regenerated by
 * `npm run test:e2e:setup` (or implicitly on the first test run via
 * `globalSetup`).
 */
export const E2E_STORAGE_STATE_PATH = "tests/fixtures/.auth/storage-state.json"
